### ISSUE TITLE
aoi removal

### ISSUE THREAD

**Issue by advasileva** [objectionary/speco#11]
Let's add a command line option to configure the removal of the `aoi` section. I suggest using the `--clear-aoi` flag to remove this section:
```
$ java -jar speco.jar --dir=/tmp/xmir --target=/tmp/xmir2 --clear-aoi
```
The default behavior will save this section.

**Comment by volodya-lombrozo** [comment]
@advasileva Perhaps we could make removal the default behavior and add an option --keep-aoi to retain the aoi section. What are your thoughts on this?

**Comment by advasileva** [comment]
@volodya-lombrozo I do not know what the default behavior is usually in such cases, maybe there is something similar in other objectionary projects? I suggested keep it by default, because `xmir` files are received as input after aoi, so the client code already knows about this section and can use it in other tasks, but this is just a guess

**Comment by volodya-lombrozo** [comment]
@advasileva Sounds reasonable. What do you think about `--clear-aoi` then? Because `--clear` doesn't tell about what exactly you are going to clean.

**Comment by advasileva** [comment]
@volodya-lombrozo I completely agree, it will be clearer this way

**Comment by advasileva** [comment]
@volodya-lombrozo Updated the issue description.

**Comment by advasileva** [comment]
I renamed the flag to `--clear-xmir` because it also removes the `<speco/>` section.
